# SPDX-License-Identifier: MIT
"""ux-valio Door A public surface.

Explicit ``__all__``. No star-import barrel, no Field, no Schema, no Cap.
``AttributeValidator`` is not exported — object-attribute presence checks
belong at the call site or on ``add_validator``.
"""

from ux_valio.descriptor import Property
from ux_valio.pattern import (
    Digit,
    EndsWith,
    IfFollowedBy,
    IfNotFollowedBy,
    IfNotPrecededBy,
    IfPrecededBy,
    NonDigit,
    NonWhiteSpace,
    NonWord,
    Pattern,
    PatternType,
    SetOf,
    StartsWith,
    WhiteSpace,
    Word,
    WordBoundary,
)
from ux_valio.validators import (
    AadhaarCardValidator,
    AllOf,
    AnyOf,
    BooleanValidator,
    BytesValidator,
    Chain,
    ChoiceValidator,
    DateValidator,
    DecimalValidator,
    EmailValidator,
    EnumValidator,
    ExpiryValidator,
    FloatValidator,
    IPAddressValidator,
    IPv4Validator,
    IPv6Validator,
    IntegerEnumValidator,
    IntegerValidator,
    LengthValidator,
    MaxLengthValidator,
    MaxValueValidator,
    MinLengthValidator,
    MinValueValidator,
    MultipleValidator,
    PathValidator,
    PaymentCardValidator,
    PANCardValidator,
    PhoneNumberValidator,
    PatternValidator,
    ReassignValidator,
    RequiredValidator,
    StringEnumValidator,
    StringValidator,
    TypeValidator,
    UUIDValidator,
    ValidateProperty,
    ValidationErrors,
    Validator,
    ValueValidator,
)

__version__ = "0.1.0"

__all__ = [
    "AadhaarCardValidator",
    "AllOf",
    "AnyOf",
    "BooleanValidator",
    "BytesValidator",
    "Chain",
    "ChoiceValidator",
    "DateValidator",
    "DecimalValidator",
    "Digit",
    "EmailValidator",
    "EndsWith",
    "EnumValidator",
    "ExpiryValidator",
    "FloatValidator",
    "IfFollowedBy",
    "IfNotFollowedBy",
    "IfNotPrecededBy",
    "IfPrecededBy",
    "IPAddressValidator",
    "IPv4Validator",
    "IPv6Validator",
    "IntegerEnumValidator",
    "IntegerValidator",
    "LengthValidator",
    "MaxLengthValidator",
    "MaxValueValidator",
    "MinLengthValidator",
    "MinValueValidator",
    "MultipleValidator",
    "NonDigit",
    "NonWhiteSpace",
    "NonWord",
    "PathValidator",
    "PANCardValidator",
    "PaymentCardValidator",
    "PhoneNumberValidator",
    "Pattern",
    "PatternType",
    "PatternValidator",
    "SetOf",
    "StartsWith",
    "Property",
    "ReassignValidator",
    "RequiredValidator",
    "StringEnumValidator",
    "StringValidator",
    "TypeValidator",
    "UUIDValidator",
    "ValidateProperty",
    "ValidationErrors",
    "Validator",
    "ValueValidator",
    "WhiteSpace",
    "Word",
    "WordBoundary",
    "__version__",
]
