# SPDX-License-Identifier: MIT
"""ux-valio Door A public surface.

Explicit ``__all__``. No star-import barrel, no Field, no Schema, no Cap.
``AttributeValidator`` is not exported — object-attribute presence checks
belong at the call site or on ``add_validator``.
"""

from ux_valio.descriptor import Property
from ux_valio.pattern import Pattern, PatternType, WordBoundary
from ux_valio.validators import (
    AllOf,
    AnyOf,
    BooleanValidator,
    BytesValidator,
    Chain,
    ChoiceValidator,
    DateValidator,
    DecimalValidator,
    EmailValidator,
    EnumValidator,
    FloatValidator,
    IPAddressValidator,
    IPv4Validator,
    IPv6Validator,
    IntegerEnumValidator,
    IntegerValidator,
    LengthValidator,
    MaxLengthValidator,
    MaxValueValidator,
    MinLengthValidator,
    MinValueValidator,
    MultipleValidator,
    PathValidator,
    PatternValidator,
    ReassignValidator,
    RequiredValidator,
    StringEnumValidator,
    StringValidator,
    TypeValidator,
    UUIDValidator,
    ValidateProperty,
    ValidationErrors,
    Validator,
    ValueValidator,
)

__version__ = "0.1.0"

__all__ = [
    "AllOf",
    "AnyOf",
    "BooleanValidator",
    "BytesValidator",
    "Chain",
    "ChoiceValidator",
    "DateValidator",
    "DecimalValidator",
    "EmailValidator",
    "EnumValidator",
    "FloatValidator",
    "IPAddressValidator",
    "IPv4Validator",
    "IPv6Validator",
    "IntegerEnumValidator",
    "IntegerValidator",
    "LengthValidator",
    "MaxLengthValidator",
    "MaxValueValidator",
    "MinLengthValidator",
    "MinValueValidator",
    "MultipleValidator",
    "PathValidator",
    "Pattern",
    "PatternType",
    "PatternValidator",
    "Property",
    "ReassignValidator",
    "RequiredValidator",
    "StringEnumValidator",
    "StringValidator",
    "TypeValidator",
    "UUIDValidator",
    "ValidateProperty",
    "ValidationErrors",
    "Validator",
    "ValueValidator",
    "WordBoundary",
    "__version__",
]
